
    - name: sample index.php
      block:
        - copy:
            dest: /var/www/html/index.php
            content: "<?php phpinfo(); ?>"
          notify: restart apache
      rescue:
        - debug:
            msg: "Failed to copy PHP file"
      always:
        - debug:
            msg: "Deployment block finished"
    - name: Install and secure MySQL
      block:
        - name: Set MySQL root password 
          mysql_user:
            name: root
            host: localhost
            password: "{{ mysql_root_password }}"
            login_unix_socket: /var/lib/mysql/mysql.sock
            state: present
      rescue:
        - name: Rescue MySQL secure install failure
          debug:
            msg: "MySQL secure installation block failed"
    - name: Configure UFW
      block:
        - name: install ufw
          yum:
            name: ufw
            state: present
            update_cache: yes
        - name: allow HTTP (80)
          ufw:
            rule: allow
            port: "80"
            proto: tcp
        - name: allow HTTPS (443)
          ufw:
            rule: allow
            port: "443"
            proto: tcp
        - name: enable ufw
          ufw:
            state: enabled